name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk unzip zlib1g-dev
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          buildozer android debug

      - uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
